src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column(length: 50)]
    private ?string $couleur = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column(length: 255)]
    private ?string $collection = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column]
    private ?int $prix = null;

    #[Assert\NotBlank(message: "ce champ ne peut être vide")] 
    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregristrement = null;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): static
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getCollection(): ?string
    {
        return $this->collection;
    }

    public function setCollection(string $collection): static
    {
        $this->collection = $collection;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getDateEnregristrement(): ?\DateTimeInterface
    {
        return $this->date_enregristrement;
    }

    public function setDateEnregristrement(\DateTimeInterface $date_enregristrement): static
    {
        $this->date_enregristrement = $date_enregristrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getProduit() === $this) {
                $commande->setProduit(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminProduitController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/admin/produit')]
class AdminProduitController extends AbstractController
{
    
    #[Route('/ajouter', name: 'ajouter_produit')]
    #[Route('/modifier/{id}', name: 'modifier_produit')]
    public function formProduct(Request $rq, EntityManagerInterface $manager, Produit $produit =null, SluggerInterface $slugger) : Response
    {
        if($produit == null)
        {
            $produit = new Produit;
            $produit->setDateEnregristrement(new \DateTime);
        }

        $editMode = $produit->getId() !== null;
        
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($rq);

        if($form->isSubmitted() && $form->isValid())
        {

            $imageFile = $form->get('photo')->getData();

            if($imageFile){
                $originalFilename = pathinfo($imageFile->getClientOriginalName(),PATHINFO_FILENAME); 
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                    try{
                        $imageFile->move(
                            $this->getParameter('img_upload'), 
                            $newFilename
                        );
                    }catch (FileException $e){

                    }
                    $produit->setPhoto($newFilename);
            } 
            
            
            $manager->persist($produit); 
            $manager->flush();

            if($editMode)
            {
                $this->addFlash('success', "La modification a été faite");
            }else{
               
                $this->addFlash('success', "Vous avez bien ajouté un nouveau produit");              
            }
            return $this->redirectToRoute('gestion_produit');

        }


        return $this->render('admin_produit/form.html.twig', [
            'form' => $form,
            'editMode' => $editMode,
        ]);

    }

    #[Route('/gestion', name:'gestion_produit')]
    public function gestion(ProduitRepository $repo): Response  
    {
        $allProducts = $repo->findAll();
        return $this->render('admin_produit/index.html.twig', [    
            'allProducts' => $allProducts,
            
        ]);
    }

    #[Route('/supprimer/{id}', name: 'supprimer_produit')]
    public function supprimer(Produit $produit, EntityManagerInterface $manager)   

    {
        $manager->remove($produit);    
        $manager->flush();     

        return $this->redirectToRoute('gestion_produit'); 
    }
   
}

templates/admin_produit/form.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{% if editMode %}
		Modifier
	{% else %}
		Ajouter
	{% endif %}
{% endblock %}


{% block body %}
<h1 class="text-center my-4">
	{% if editMode %}
		Modifier
	{% else %}
		Ajouter
	{% endif %}
	un produit</h1>


<div class="container">
	{{ form_start(form, {
            attr: { novalidate: "novalidate"}
        })}}
	{{form_row(form.titre) }}
	{{form_row(form.description) }}
	{{form_row(form.couleur) }}
	{{form_row(form.collection) }}
	{{form_row(form.photo) }}
	{{form_row(form.prix) }}
	{{form_row(form.stock) }}

	{{ form_end(form)}}
</div>
{% endblock %}

templates/admin_produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Gestion des produits
{% endblock %}

{% block body %}

<div class="container">
<a class="btn btn-primary mb-1 mt-5" href="{{ path('ajouter_produit')}}" role="button">Ajouter un produit</a>
</div>

	<div class="container mt-5">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">titre</th>
					<th scope="col">description</th>
					<th scope="col">couleur</th>
					<th scope="col">Collection</th>
					<th scope="col">Photo</th>
					<th scope="col">Prix</th>
					<th scope="col">Stock</th>
					<th scope="col">Date Enregistrement</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for produit in allProducts %}


					<tr class="table-active">
						<td>{{produit.id}}</td>
						<td>{{produit.titre}}</td>
						<td>{{produit.description}}</td>
						<td>{{produit.couleur}}</td>
						<td>{{produit.collection}}</td>
						<td><img src="{{ asset('uploads/photos/' ~ produit.photo) }}" alt="" width="60"></td>
						<td>{{produit.prix}}</td>
						<td>{{produit.stock}}</td>
						<td>{{produit.dateEnregristrement|date('d/m/Y')}}</td>
						<td>
							<a href="{{ path('modifier_produit', {id: produit.id} ) }}">
								<i class="bi bi-pencil-square"></i>
							</a>
							<a href="{{ path('supprimer_produit', {id: produit.id} ) }}">
								<i class="bi bi-trash3"></i>
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	</div>


{% endblock %}